#!/bin/bash

help() {

	echo Usage: medialib [OPTIONS]
	echo
	echo Options:
	echo '	-h			Print this help and exit.'
    echo '	-a			Create symlinks for each show and then renames them afterwards'
    echo '	-d <directory>		Define symlink directory'
    echo '  -e          Edit your shows'
    echo '	-i	<tv|tmov|t>	Set library mode'
	echo '	-f <directory>		Add Parent source'
	echo '	-F <directory>		Remove Parent source'
    echo '	-l			List infortmation , tests source and previews various variables'
    echo
    echo 'Setup 'custom-rename' file in "~/.config/medialib" for custom renaming afterwards'
    echo 'Setup 'custom-special' file in ~/.config/medialib for Special episodes in TV Shows'
    echo ' '
	
}